aws_flavor = "c4.large"
aws_key_name = "github-backup"
aws_region = "us-west-2"
dns_zone_id = "Z3651YA2BWMOR9"
dns_name = "github-backup.eng.xogrp.com"
aws_subnet_id="subnet-ea60929d"
aws_vpc_id="vpc-b403c3d1"
aws_private_key_file="/User/chuey/.ssh/github-backup.pem"
